### ISSUE TITLE
[Requirement] Rezeptesammlung

### ISSUE THREAD

**Issue by ghost** [felix185/pluto#10]
## Szenario: Rezept eintragen

Ich bin Anwender (Student)
UND habe eine Eingabemaske zum Anlegen von Rezepten geöffnet
WENN ich Zutaten definiere
UND eine Kochanleitung dazu schreibe
UND bestätige
DANN merkt sich die Anwendung dieses Rezept.
## Szenario2: Rezepte Übersicht anzeigen

Ich bin Anwender (Student)
UND befinde mich auf der Übersichtsseite der Rezepte
DANN sehe ich alle Rezepte die die Anwendung kennt.
## Szenario3: Rezepte löschen

Ich bin Anwender (Student)
UND befinde mich auf der Übersichtsseite der Rezepte.
WENN ich auf den Button "Rezept löschen" klicke
DANN wird das entsprechende Rezept gelöscht.

Diese Anforderung ist (1 \* count(Teammitglieder)) Punkte für die Gruppe wert. 
Alle oben genannten Akzeptanzkriterien müssen erfolgreich erfüllt 
sein, um die Punkte zu bekommen.

**Comment by gnampfelix** [comment]
Erstellen
Frontend -> Backend
[
incredients
[
name
amount
]
title
text
author

Anzeigen:
Backend -> Frontend
[
recipes
[
incredients
[
name
amount
]
title
text
author
id
]
]

Löschen:
Frontend->Backend
id

**Comment by gnampfelix** [comment]
Tippfehler beachten: Backend verwendet "Ingredients" statt "Incredients"
