### ISSUE TITLE
[Requirement] Rezeptabfrage

### ISSUE THREAD

**Issue by ghost** [felix185/pluto#11]
## Szenario: Passendes Rezept finden

Ich bin Anwender (Student)
UND befinde mich auf einer Seite zur Eingabe meiner Zutaten.
WENN ich die Zutaten eingetragen habe
UND bestätige
DANN bekomme ich eine Liste mit passenden Rezepten dargestellt.

Diese Anforderung ist (1 \* count(Teammitglieder)) Punkte für die Gruppe wert. 
Alle oben genannten Akzeptanzkriterien müssen erfolgreich erfüllt 
sein, um die Punkte zu bekommen.

**Comment by hauseralex** [comment]
**Variablen:**
_Frontend -> Backend_
[
   incredients 
   [
      name
      amount
   ]
]

_Backend -> Frontend_
[
   recipes
      [
      incredients
         [
         name
         amount
         ]
      title
      text
      author
      score
      ]
]

**Comment by gnampfelix** [comment]
Tippfehler beachten: Backend verwendet "Ingredients" statt "Incredients"
