### ISSUE TITLE
[Requirement] Aktivitätenstream

### ISSUE THREAD

**Issue by ghost** [felix185/pluto#12]
## Szenario: Aktivitäten anzeigen

Ich bin Anwender
UND befinde mich auf der Startseite der Anwendung
DANN wird mir ein Aktivitätenstream angezeigt.
## Szenario2: Aktivitäten speichern

WENN eine Aktivität (Rezept anlegen, löschen, suchen, Waschalarm anlegen, benachrichtigen) passiert
DANN merkt sich die Anwendung diese.

Diese Anforderung ist (1 \* count(Teammitglieder)) Punkte für die Gruppe wert. 
Alle oben genannten Akzeptanzkriterien müssen erfolgreich erfüllt 
sein, um die Punkte zu bekommen.

**Comment by hauseralex** [comment]
**Variablen:**
_Backend -> Frontend_
activity
eMail
timestamp

**Comment by gnampfelix** [comment]
DB-Table:

CREATE TABLE activities (
id INT PRIMARY KEY,
description VARCHAR(255),
eMail VARCHAR(255),
timestamp LONG);
