### ISSUE TITLE
[Requirement] Waschinstruktionen

### ISSUE THREAD

**Issue by ghost** [felix185/pluto#13]
## Szenario: Übersicht

Ich bin Anwender 
UND befinde mich auf einer Übersichtsseite der Anwendung
DANN werden mir zu den Pfelegesymbole für Wäsche entsrechende Informationen angezeigt.
## Szenario2: Suche nach Waschsymbolen

Ich bin Anwender
UND befinde mich auf der Übersichtsseite für Waschinstruktionen.
WENN ich in einem Suchfeld einen Wert eintrage
DANN werden alle Pflegehinweise ausgeblendet, die nicht zu der Sucheingabe passen.

Diese Anforderung ist (1 \* count(Teammitglieder)) Punkte für die Gruppe wert. 
Alle oben genannten Akzeptanzkriterien müssen erfolgreich erfüllt 
sein, um die Punkte zu bekommen.

**Comment by hauseralex** [comment]
**Variablen:**
_Backend -> Frontend_
[
  url
  name
  description
  tags [
    name
  ]
]

**Comment by gnampfelix** [comment]
DB Tables:
CREATE TABLE laundryIcon (id INTEGER PRIMARY KEY, url VARCHAR(255), description
VARCHAR(3000), name VARCHAR(255));

CREATE TABLE tags (id INTEGER PRIMARY KEY, name VARCHAR(255));

CREATE TABLE iconTags (tagID INTEGER, iconID INTEGER);

CREATE VIEW laundryIconView AS
SELECT icon.url AS url, icon.name AS name, icon.description AS description, GROUP_CONCAT(tags.name) AS tags 
FROM laundryIcon AS icon 
JOIN iconTags ON icon.id = iconTags.iconID 
JOIN tags ON iconTags.tagID = tags.id 
GROUP BY icon.id;
