### ISSUE TITLE
[Requirement] Wäschealarm

### ISSUE THREAD

**Issue by ghost** [felix185/pluto#14]
## Szenario: Alarm konfigurieren

Ich bin Anwender
UND habe eine Eingabemaske für einen Wäschealarm geöffnet
WENN ich einen Zeitraum eintrage
UND einen E-Mail Empfänger definiere
UND bestätige
DANN erzeugt die Anwendung eine entsprechende Alarm-Erinnerung.
## Szenario2: Alarm Benachrichtigung per E-Mail

Ich bin Anwender
UND habw einen Wäschealarm konfiguriert.
WENN der Zeitpunkt für den Alarm gekommen ist
DANN sendet die Anwendung dem konfigurierten Empfänger eine E-Mail Erinnerung.

Diese Anforderung ist (1 \* count(Teammitglieder)) Punkte für die Gruppe wert. 
Alle oben genannten Akzeptanzkriterien müssen erfolgreich erfüllt 
sein, um die Punkte zu bekommen.

**Comment by hauseralex** [comment]
**Variablen:** 
_Frontend -> Backend_
eMail
alarmTime (= Uhrzeit)
